log_path:
  - D:/User-Documents/Desktop/{environment}-{user}/logs/
  - D:/User-Documents/Desktop/{environment}-{user}/pre-upload-processing/

sources:
  - master_source
  - master_config
  - source_1
  - source_2

master_source:
  type: grouped_file_format
  days: ['daily']
  max_row_count: 3000000
  child_sources:
    - master_source_child_source_1
    - master_source_child_source_2
  columns:
    SourceName:
      dtype: string
      max—length: 60
    ColumnName:
      dtype: string
      casing: mixed
      max_length: 60
    ID:
      dtype: integer
      min: 0
      max_length: 3000000
    Value:
      dtype: string
      casing: mixed

master_config:
  type: grouped_file_format
  days: ['daily']
  max_row_count: 3000000
  child_sources:
    - master_config_child_source_1
    - master_config_child_source_2
  columns:
    SourceName:
      dtype: string
      max—length: 60
    ColumnName :
      dtype: string
      casing: mixed
      max_length: 60
    ID:
      dtype: integer
      min: 0
      max_length: 3000000
    Value:
      dtype: string
      casing: mixed

master_source_child_source_1:
  type: long_file_format
  days: [0]
  required: False
  source_files:
    local_path: D:/User-Documents/Desktop/{environment}-{user}/sources/master_source_child_source_1/
    file: source_file.csv
    extension: csv
    load_type: single
  columns:
    source_column_1:
      dtype: string
      rename_from: SourceColumn_1
      is_key: true
      pre-processing:
        - dropout
        - nullable
      validation:
        casing: mixed
        max_length: 60
    source_column_2:
      dtype: string
      rename_from: SourceColumn_2
      is_key: true

master_source_child_source_2:
  type: long_file_format
  days: [0]
  required: False
  source_files:
    local_path: D:/User-Documents/Desktop/{environment}-{user}/sources/master_source_child_source_2/
    file: source_file.csv
    extension: csv
    load_type: single
  columns:
    source_column_1:
      dtype: string
      rename_from: SourceColumn_1
      is_key: true
      pre-processing:
        - dropout
        - nullable
      validation:
        casing: mixed
        max_length: 60
    source_column_2:
      dtype: string
      rename_from: SourceColumn_2
      is_key: true

master_config_child_source_1:
  type: long_file_format
  days: [0]
  required: False
  source_files:
    local_path: D:/User-Documents/Desktop/{environment}-{user}/sources/master_config_child_source_1/
    file: source_file.csv
    extension: csv
    load_type: single
  columns:
    source_column_1:
      dtype: string
      rename_from: SourceColumn_1
      is_key: true
      pre-processing:
        - dropout
        - nullable
      validation:
        casing: mixed
        max_length: 60
    source_column_2:
      dtype: string
      rename_from: SourceColumn_2
      is_key: true

master_config_child_source_2:
  type: long_file_format
  days: [0]
  required: False
  source_files:
    local_path: D:/User-Documents/Desktop/{environment}-{user}/sources/master_config_child_source_2/
    file: source_file.csv
    extension: csv
    load_type: single
  columns:
    source_column_1:
      dtype: string
      rename_from: SourceColumn_1
      is_key: true
      pre-processing:
        - dropout
        - nullable
      validation:
        casing: mixed
        max_length: 60
    source_column_2:
      dtype: string
      rename_from: SourceColumn_2
      is_key: true

source_1:
  type: default_file_format
  days: [0]
  required: False
  source_files:
    local_path: D:/User-Documents/Desktop/{environment}-{user}/sources/source_1/
    file: source_file.csv
    extension: csv
    load_type: single
  columns:
    source_column_1:
      dtype: string
      rename_from: SourceColumn_1
      is_key: true
      pre-processing:
        - dropout
        - nullable
      validation:
        casing: mixed
        max_length: 60
    source_column_2:
      dtype: string
      rename_from: SourceColumn_2
      is_key: true


source_2:
  type: default_file_format
  days: [0]
  required: False
  source_files:
    local_path: D:/User-Documents/Desktop/{environment}-{user}/sources/source_1/
    file: source_file_*.xlsx
    extension: xlsx
    load_type: bulk
  columns:
    source_column_1:
      dtype: string
      rename_from: SourceColumn_1
      is_key: true
      pre-processing:
        - dropout
        - nullable
      validation:
        casing: mixed
        max_length: 60
    source_column_2:
      dtype: string
      rename_from: SourceColumn_2
      is_key: true
