name: Feature Request
description: Suggest a new feature or improvement.
title: "[Feature Request]: <Title>"
type: feature
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: What feature would you like to see?
      placeholder: 
    validations:
      required: true
  - type: textarea
    id: why-needed
    attributes:
      label: Why Is This Needed?
      description: Explain the problem or need for this feature.
      placeholder: What problem would you like us to solve?
    validations:
      required: true
  - type: textarea
    id: suggested-solution
    attributes:
      label: Suggested Solutions
      description: Describe how this feature could be implemented.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any relevant screenshots, links, or resources.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](docs/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
