name: Task
description: Describe a Task.
title: "[Task]: <Title>"
type: task
body:
  - type: markdown
    attributes:
      value: |
        Describe the task.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What needs to be done?
      placeholder: 
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: What are the Acceptance Criteria?
      description: Describe the Acceptance Criteria for this task.
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](docs/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
