name: Task
description: Task under a bug or feature.
title: "[Task]: <Title>"
type: task
body:
  - type: markdown
    attributes:
      value: |
        Describe the task.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What feature would you like to see?
      placeholder: 
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: What are the Acceptance Criteria?
      description: Describe the Acceptance Criteria for this task.
    validations:
      required: true
